cryptocollector_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('coins/', views.index, name='index'),
    path('coins/new/', views.add_coin, name='add_coin'),
    path('coins/<int:coin_id>/', views.coins_detail, name='coins_detail'),
    path('coins/<int:coin_id>/edit/', views.coins_edit, name='coins_edit'),
    path('coins/<int:coin_id>/delete/', views.coins_delete, name='coins_delete'),
    path('coins/<int:coin_id>/historical_data/', views.coins_add_historical_data, name='coins_add_historical_data'),
    path('coins/<int:coin_id>/exchange/<int:exchange_id>/add/', views.add_exchange, name='add_exchange'),
    path('coins/<int:coin_id>/exchange/<int:exchange_id>/remove/', views.remove_exchange, name='remove_exchange'),
    path('accounts/signup/', views.signup, name='signup'),
    path('historical_data/<int:data_id>/delete', views.delete_historical_data , name='delete_historical_data'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Exchange(models.Model):
    name = models.CharField(max_length=50)
    website = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    

class CryptoCurrency(models.Model):
    name = models.CharField(max_length=100)
    ticker_symbol = models.CharField(max_length=100)
    about = models.TextField(max_length=5000)
    current_price_usd = models.DecimalField(max_digits=20, decimal_places=10)
    market_cap_usd = models.CharField(max_length=50)
    exchanges = models.ManyToManyField(Exchange, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} ({self.ticker_symbol})'
    

class HistoricalData(models.Model):
    date = models.DateField()
    open = models.DecimalField(max_digits=20, decimal_places=10)
    close = models.DecimalField(max_digits=20, decimal_places=10)
    cryptocurrency = models.ForeignKey(CryptoCurrency, on_delete=models.CASCADE)

main_app/forms.py
from django import forms
from .models import CryptoCurrency, HistoricalData

class CryptoCurrencyForm(forms.ModelForm):
    class Meta:
        model = CryptoCurrency
        fields = ('name', 'ticker_symbol', 'about', 'current_price_usd', 'market_cap_usd')

class HistoricalDataForm(forms.ModelForm):
    class Meta:
        model = HistoricalData
        fields = ('date', 'open', 'close')

main_app/views.py
from django.shortcuts import render, redirect
from .models import CryptoCurrency, Exchange, HistoricalData
from .forms import CryptoCurrencyForm, HistoricalDataForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.db.models import Q

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')


@login_required
def index(request):
    url_parameter = request.GET.get("q")
    if url_parameter:
        matching_coins = CryptoCurrency.objects.filter(
            Q(user=request.user), 
            Q(ticker_symbol__icontains=url_parameter) | Q(name__icontains=url_parameter)
        )
    else:
        matching_coins = CryptoCurrency.objects.filter(user=request.user)
        
    context = {
        'coins': matching_coins
    }
    if request.is_ajax():
        html = render_to_string(
            template_name = "coins/coins_results_partial.html", 
            context={'coins': matching_coins}
        )
        data_dict = {
            "html_from_view": html
        }
        return JsonResponse(data=data_dict, safe=False)
    return render(request, 'coins/coins_index.html', context)

@login_required
def coins_detail(request, coin_id):
    coin = CryptoCurrency.objects.get(id=coin_id)
    form = HistoricalDataForm()
    remaining_exchanges = Exchange.objects.exclude(cryptocurrency=coin_id)
    context = {
        'coin': coin,
        'form': form,
        'remaining_exchanges': remaining_exchanges
    }
    return render(request, 'coins/coins_detail.html', context)

@login_required
def add_coin(request):
    if request.method == 'GET':
        form = CryptoCurrencyForm()
        context = {
            'form': form
        }
        return render(request, 'coins/coins_new.html', context)
    else:
        form = CryptoCurrencyForm(request.POST)
        if form.is_valid():
            coin = form.save(commit=False)
            coin.user = request.user
            coin.save()
            return redirect('coins_detail', coin.id)

@login_required
def coins_edit(request, coin_id):
    coin = CryptoCurrency.objects.get(id=coin_id)
    if request.method == 'GET':
        form = CryptoCurrencyForm(instance=coin)
        context = {
            'form': form
        }
        return render(request, 'coins/coins_edit.html', context)
    else:
        form = CryptoCurrencyForm(request.POST, instance=coin)
        if form.is_valid():
            form.save()
            return redirect('coins_detail', coin.id)

@login_required
def coins_delete(request, coin_id):
    CryptoCurrency.objects.get(id=coin_id).delete()
    return redirect('index')

@login_required
def coins_add_historical_data(request, coin_id):
    form = HistoricalDataForm(request.POST)
    if form.is_valid():
        data = form.save(commit=False)
        data.cryptocurrency_id = coin_id
        data.save()
        return redirect('coins_detail', coin_id)

@login_required
def add_exchange(request, coin_id, exchange_id):
    CryptoCurrency.objects.get(id=coin_id).exchanges.add(exchange_id)
    return redirect('coins_detail', coin_id)

@login_required
def remove_exchange(request, coin_id, exchange_id):
    CryptoCurrency.objects.get(id=coin_id).exchanges.remove(exchange_id)
    return redirect('coins_detail', coin_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            print('==============')
            print(user.__dict__)
            print('==============')
            # Auto login the user upon sucessful signup
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid username and/or password'
    form = UserCreationForm()
    context = {
        'form': form,
        'error_message': error_message
    }
    return render(request, 'registration/signup.html', context)

@login_required
def delete_historical_data(request, data_id):
    data = HistoricalData.objects.get(id=data_id)
    coin_id = data.cryptocurrency_id
    HistoricalData.objects.get(id=data_id).delete()
    return redirect('coins_detail', coin_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>About the Crypto Collector</h1>
    <hr/>
    <p>She collects all the right coins!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Materialize CSS -->
    <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <!-- Materialize JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!--  <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    /> -->
    <!-- jQuery  -->
    <script
    src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"></script>
    <!-- FontAwesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300&display=swap" rel="stylesheet">
    
    <title>CryptoCollector</title>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
                <a href="/" class="left brand-logo">
                <span id="crypto-logo">
                    <img class="coin-logo-img" src="{% static 'images/CryptoLogo.png' %}" alt=""/>
                </span>
                  CryptoCollector
                </a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'home' %}">Home</a></li>
             <li><a href="{% url 'about' %}">About</a></li>
             {% if user.is_authenticated %}
              <li><a href="{% url 'add_coin' %}">Add Coin</a></li>
              <li><a href="{% url 'index' %}">All Cryptos</a></li>
              <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
              <li><a href="{% url 'login' %}">Login</a></li>
              <li><a href="{% url 'signup' %}">Signup</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>

    <main class="container">
      {% block content %}
      {% endblock %}
    </main>

    <footer class="page-footer">
      <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
      <div class="right">
        All Rights Reserved, &copy; 2021 Crypto Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/coins/coins_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ coin.name }} ({{ coin.ticker_symbol }}) Detail</h1>
    <div class="row">
        <div class="col s6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{ coin.name }} ({{ coin.ticker_symbol }})</span>
                    <p><span class="bold">Current Price (USD):</span> {{ coin.current_price_usd }}</p>
                    <p><span class="bold">Market Cap (USD):</span> {{ coin.market_cap_usd }}</p>
                    <p><span class="bold">About:</span> {{ coin.about}} </p>
                </div>

                {% comment %} Edit and Delete buttons {% endcomment %}
                <div class="card-action">
                    <a href="{% url 'coins_delete' coin.id %}">Delete</a>
                    <a href="{% url 'coins_edit' coin.id %}">Edit</a>
                </div>
            </div>
        </div>

        <div class="col s6">
            <form action="{% url 'coins_add_historical_data' coin.id %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn" type="submit">Add Data</button>
            </form>

            <h4>Historical Data</h4>
            {% if coin.historicaldata_set.count %}
                <table class="striped">
                    <thead>
                        <tr><th>Date</th><th>Open</th><th>Close</th><th>Delete</th></tr>
                    </thead>
                    <tbody>
                        {% for data in coin.historicaldata_set.all %}
                            <tr>
                                <td>{{ data.date }}</td>
                                <td>{{ data.open }}</td>
                                <td>{{ data.close }}</td>
                                <td><form action="{% url 'delete_historical_data' data.id %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn" type="submit">Delete</button>
                                </form></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No historical data is available at this time.</p>
            {% endif %}
        </div>
    </div>

        <hr />

        <div class="row">
            <div class="col s6">
                <h3>Trades on</h3>
                {% if coin.exchanges.count %}
                    {% for exchange in coin.exchanges.all %}
                        <div class="card">
                            <div class="card-content">
                                <span class="card-title"><a href="http://{{ exchange.website }}">{{ exchange.name }}</a></span>
                            </div>
                            <div class="card-action">
                                <form action="{% url 'remove_exchange' coin.id exchange.id %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn" type="submit">Remove</button>
                                </form>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>This coin is not currently available to trade on any exchange in US.</p>
                {% endif %}
            </div>

            <div class="col s6">
                <h3>Available Exchanges</h3>
                    {% for exchange in remaining_exchanges %}
                        <div class="card">
                            <div class="card-content">
                                <span class="card-title"><a href="http://{{ exchange.website }}">{{ exchange.name }}</a></span>
                            </div>
                            <div class="card-action">
                                <form action="{% url 'add_exchange' coin.id exchange.id %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn" type="submit">Add</button>
                                </form>
                            </div>
                        </div>
                    {% endfor %}
            </div>
        </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const dates = document.querySelectorAll('#id_date');

            const options = {
            format: 'yyyy-mm-dd',
            defaultDate: new Date(),
            setDefaultDate: true,
            autoClose: true,
            }

            const dateInstances = M.Datepicker.init(dates, options);
        });
    </script>

{% endblock %}

main_app/templates/coins/coins_edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>Update Coin Info</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn" type="submit">Update</button>
    </form>
{% endblock %}

main_app/templates/coins/coins_index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Coins List</h1>
    <div id="search-bar-container">
        <i id="search-icon" class="fas fa-search fa-2x"></i>
            <input type="text" name="search-coins" id="user-input" placeholder="Search by ticker symbol or name">
        
    </div>

    <div id="replaceable-content">
        {% include 'coins/coins_results_partial.html' %}
    </div>
{% endblock %}

main_app/templates/coins/coins_new.html
{% extends 'base.html' %}

{% block content %}
    <h1>Add a new coin</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn" type="submit">Add Coin</button>
    </form>
{% endblock %}

main_app/templates/coins/coins_results_partial.html
{% if coins %}
    {% for coin in coins %}
        <a href="{% url 'coins_detail' coin.id %}">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{ coin.name }} ({{ coin.ticker_symbol }})</span>
                    <p>Current price (USD): {{ coin.current_price_usd}}</p>
                    <p>Market Cap (USD): {{ coin.market_cap_usd}}</p>
                </div>
            </div>
        </a>
    {% endfor %}
{% else %}
    <p>No results found</p>
{% endif %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to the CryptoCollector</h1>
    <p>Recruiters, please use neha/abc123 credentials to login and check out the functionality, if you do not wish to create an account.</p>
{% endblock %}